#pragma once

enum class ToolType {
    BRUSH_BLOCK,
    BRUSH_LINE,
    BRUSH_RECT,
    BRUSH_RECT_FILLED,
    BRUSH_CIRCLE,
    BRUSH_CIRCLE_FILLED,
    BRUSH_FILL,
    BRUSH_COPY,
    BRUSH_INVALID
};